apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iframely.fullname" . }}
  labels:
    {{- include "iframely.labels" . | nindent 4 }}
data:
  config:
{{ toYaml .Values.config | indent 4 }}
