{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "iframely.serviceAccountName" . }}
  labels:
{{ include "iframely.labels" . | nindent 4 }}
{{- end -}}
