apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "beanstalkd.fullname" . }}
  labels:
    app: {{ template "beanstalkd.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.beanstalkd.binlogSize | quote }}
